# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('total_time', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'media')),
                ('type', models.IntegerField(choices=[(0, b'veg'), (1, b'non-veg')], default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Ingridient',
                'verbose_name_plural': 'Ingridients',
            },
        ),
        migrations.CreateModel(
            name='IngridientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Dish')),
                ('ingridient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Ingridient')),
            ],
            options={
                'verbose_name': 'Ingridient List',
                'verbose_name_plural': 'Ingridient Lists',
            },
        ),
        migrations.CreateModel(
            name='step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=150)),
                ('time', models.FloatField()),
                ('description', models.TextField(default=None, null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Measure',
                'verbose_name_plural': 'Measurements',
            },
        ),
        migrations.AddField(
            model_name='ingridientlist',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Unit'),
        ),
    ]
