# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Dish', 'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterModelOptions(
            name='ingridient',
            options={'verbose_name': 'Ingridient', 'verbose_name_plural': 'Ingridients'},
        ),
        migrations.AlterModelOptions(
            name='ingridientlist',
            options={'verbose_name': 'Ingridient List', 'verbose_name_plural': 'Ingridient Lists'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Measure', 'verbose_name_plural': 'Measurements'},
        ),
        migrations.AlterField(
            model_name='ingridientlist',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Dish'),
        ),
    ]
