# Generated by Django 2.0.1 on 2018-01-06 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis', '0001_initial'),
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appuser.Kitchen'),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('dish', 'step_name')},
        ),
    ]
