# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appuser', '0001_initial'),
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appuser.Book'),
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set([('dish', 'step_name')]),
        ),
    ]
