# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20170521_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
